project:
  type: book
  output-dir: docs

book:
  title: "Silabus PKSL"
  subtitle: "MKK151304"
  author: "Sunu Bagaskara"
  date: last-modified
  date-format: "D MMMM YYYY"
  chapters:
    - index.qmd
    - ringkasan.qmd
    - materi.qmd
    - komponen.qmd
    - policies.qmd
    - jadwal.qmd
  sidebar: 
    style: docked
  downloads: [pdf]
  
bibliography: references.bib

format:
  html:
    theme:
      - united
      - brand
    respect-user-color-scheme: true
    toc: true
    toc-depth: 3
    toc-expand: 3
    title-block-banner: true
  pdf:
    documentclass: scrbook
    breadcrumb: true
  
editor: visual

