project:
  type: book
  output-dir: docs

book:
  title: "Silabus PKSL"
  author: "Sunu Bagaskara"
  date: "8/18/2025"
  chapters:
    - index.qmd
    - ringkasan.qmd
    - materi.qmd
    - komponen.qmd
    - policies.qmd
    - jadwal.qmd
  sidebar: 
    style: docked
  downloads: [pdf]
  
bibliography: references.bib

format:
  html:
    theme:
      - united
      - brand
    respect-user-color-scheme: true
    toc: true
    toc-depth: 3
    toc-expand: 3
  
  pdf:
    documentclass: scrreprt
  
  
editor: visual

