# Kebijakan Kelas {.unnumbered}

## Kehadiran

Kami mendorong kalian untuk menghadiri setiap sesi kelas. Meskipun kehadiran di kelas ini tidak diwajibkan secara eksplisit, tetapi hal itu akan menurunkan kepercayaan kelompok kalian jika mereka sering melihat kalian tidak masuk kelas.

Berikut sejumlah hal yang harus kalian lakukan jika kalian tidak dapat masuk kelas:

-   Bicaralah dengan teman sekelas untuk mencari tahu informasi apa yang kalian lewatkan
-   Periksa LAYAR untuk melihat handout materi kuliah atau perubahan tugas yang diberikan
-   Kirimkan pesan kepada dosen pengampu jika kalian punya pertanyaan mengenai tugas dan materi yang tidak dapat kalian pahami
-   Jika kalian tidak dapat masuk kelas beberapa pertemuan, silakan datang dan bicaralah dengan dosen pengampu. Apabila ada sesuatu yang menghalangi kalian untuk hadir (masalah kesehatan/psikologis/keluarga/keuangan) mari kita cari tahu apa itu dan bagaimana kami dapat membantu.

::: callout-important
Kehadiran fisik di kelas tidak lebih penting daripada pemahaman kalian mengenai materi yang disampaikan. Tugas yang dikerjakan dengan baik, partisipasi aktif, dan nilai ujian yang tinggi lebih diapresiasi daripada kehadiran rutin tanpa bukti pemahaman.
:::

## Plagiarisme & Integritas Akademik {#sec-plagiat}

Kami berharap kalian memahami apa itu plagiarisme dan apa yang bukan. **Plagiarisme berarti mengambil pekerjaan orang lain dan mengakuinya sebagai pekerjaan sendiri tanpa mencantumkan sumber.** Kalian tidak boleh menyalin karya orang lain, dan tidak boleh hanya mengubah kata-kata dari sumber lain tanpa memberikan kredit. Jika menggunakan ide, data, atau tulisan orang lain, wajib mencantumkan sitasi. Tulislah dengan kata-kata kalian sendiri. Jika kalian ragu apakah suatu hal termasuk plagiarisme atau tidak, silakan tanyakan pada dosen pengampu. Mahasiswa yang terbukti melakukan plagiarisme akan dilaporkan ke Kepala Prodi, mendapatkan nilai nol untuk tugas tersebut, dan bisa dinyatakan tidak lulus dalam mata kuliah ini.

Kuis dan tugas-tugas individu harus dikerjakan secara mandiri. Namun, kami mendorong kalian untuk dapat bekerja sama dengan teman sekelas untuk tugas dan penilaian lainnya. Proyek dan tugas kelompok wajib dikerjakan bersama. Belajar bersama dalam kelompok sangat dianjurkan karena membantu memahami materi, tetapi pastikan kalian tetap bisa menjawab pertanyaan secara mandiri. Kami percaya bahwa kalian mengikuti mata kuliah ini dengan tujuan belajar sebaik-baiknya dan menjaga integritas akademik.

## Penggunaan Ponsel & Laptop

Sebelum masuk kelas, pastikan kalian sudah menonaktifkan ponsel atau menggunakan mode *silent.* Kalian tidak boleh menggunakan ponsel selama kelas kecuali diminta (misalnya, untuk mengisi survei). Kami tidak menyarankan untuk mencatat di ponsel atau laptop kecuali kalian tidak memiliki buku catatan.

Jika kalian mengirim pesan teks atau mengakses materi/laman website yang tidak terkait dengan kelas selama jam pelajaran, kalian dianggap absen secara mental dari kelas. Di sesi praktik, kita akan menggunakan lab komputer. Penggunaan laptop tidak dianjurkan, kecuali untuk mengakses dataset yang relevan dengan sesi praktik. Kami menganjurkan kalian untuk menonaktifkan notifikasi/mengaktifkan fitur Do Not Disturb sebisa mungkin. Melihat materi yang tidak relevan akan mengganggu kalian dan juga teman sekelas kalian.

::: callout-tip
Bijaklah dalam menggunakan segala bentuk *gadget* selama sesi kuliah. Jangan biarkan kegiatan-kegiatan & informasi-informasi yang tidak relevan dengan materi kuliah mendistraksi fokus kalian, yang nantinya berdampak negatif terhadap pemahaman materi kuliah.
:::

## Keterlambatan Pengumpulan Tugas

Tugas tugas pribadi maupun kelompok dapat dikumpulkan dalam waktu selambat-lambatnya 12 jam dari tenggat waktu yang ditetapkan tanpa dikenakan pemotongan nilai. Misalnya, jika tugas harus dikumpulkan pkl. 16.00 WIB pada hari Rabu, tugas tersebut dapat dikumpulkan paling lambat Kamis pagi pkl. 04.00 WIB tanpa pengurangan nilai. Tugas masih dapat dikumpulkan setelah batas waktu tersebut. Namun, tugas-tugas tersebut dianggap "Sangat Terlambat". Tugas tersebut tidak akan diberi nilai penuh.

::: callout-caution
Jika tugas kalian selalu terlambat dikumpulkan, hal ini juga dapat memengaruhi nilai kalian, kecuali kalian membicarakan keterlambatan ini dengan dosen pengampu.
:::
